style:
  MagicNumber:
    active: false
  MaxLineLength:
    active: false
  UnusedPrivateMember:
    ignoreAnnotated:
      - Preview

naming:
  FunctionNaming:
    ignoreAnnotated:
      - Composable
      - Preview
